### ISSUE TITLE
CRUD Operations with flask

### ISSUE THREAD

**Issue by xxshubhamxx** [praveen17DS/flask_oracle_db_datastore#1]
Hey, can we develop this application to perform all CRUD opearations instead of only create operation? I need to check a crud app in flask

**Comment by praveen17DS** [comment]
Yaaaa, sure we can develop all the CRUD operations by flask.

**Comment by xxshubhamxx** [comment]
Thanks for the reply, but actually I'm sorry, I just finished developing it myself alone. I have uploaded the code at https://github.com/xxshubhamxx/flask-oracle-crud so you can check it out if you want to :)
